#include <avr/pgmspace.h>
#include "programs.h"
const PROGMEM line program_dice[] = {
{2, "PRINT TAB(34);\"DICE\"\n"},
{4, "PRINT TAB(15);\"CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY\"\n"},
{6, "PRINT:PRINT:PRINT\n"},
{10, "DIM F(12)\n"},
{20, "REM  DANNY FREIDUS\n"},
{30, "PRINT \"THIS PROGRAM SIMULATES THE ROLLING OF A\"\n"},
{40, "PRINT \"PAIR OF DICE.\"\n"},
{50, "PRINT \"YOU ENTER THE NUMBER OF TIMES YOU WANT THE COMPUTER TO\"\n"},
{60, "PRINT \"'ROLL' THE DICE.  WATCH OUT, VERY LARGE NUMBERS TAKE\"\n"},
{70, "PRINT \"A LONG TIME.  IN PARTICULAR, NUMBERS OVER 5000.\"\n"},
{80, "FOR Q=1 TO 12\n"},
{90, "F(Q)=0\n"},
{100, "NEXT Q\n"},
{110, "PRINT:PRINT \"HOW MANY ROLLS\";\n"},
{120, "INPUT X\n"},
{130, "FOR S=1 TO X\n"},
{140, "A=INT(6*RND(1)+1)\n"},
{150, "B=INT(6*RND(1)+1)\n"},
{160, "R=A+B\n"},
{170, "F(R)=F(R)+1\n"},
{180, "NEXT S\n"},
{185, "PRINT\n"},
{190, "PRINT \"TOTAL SPOTS\",\"NUMBER OF TIMES\"\n"},
{200, "FOR V=2 TO 12\n"},
{210, "PRINT V,F(V)\n"},
{220, "NEXT V\n"},
{221, "PRINT\n"},
{222, "PRINT:PRINT \"TRY AGAIN\";\n"},
{223, "INPUT Z$\n"},
{224, "IF Z$=\"YES\" THEN 80\n"},
{240, "END\n"},
{},
};
