#include <avr/pgmspace.h>
#include "programs.h"
const PROGMEM line program_guess[] = {
{1, "PRINT TAB(33);\"GUESS\"\n"},
{2, "PRINT TAB(15);\"CREATIVE COMPUTING  MORRISTOWN, NEW JERSEY\"\n"},
{3, "PRINT:PRINT:PRINT\n"},
{4, "PRINT \"THIS IS A NUMBER GUESSING GAME. I'LL THINK\"\n"},
{5, "PRINT \"OF A NUMBER BETWEEN 1 AND ANY LIMIT YOU WANT.\"\n"},
{6, "PRINT \"THEN YOU HAVE TO GUESS WHAT IT IS.\"\n"},
{7, "PRINT\n"},
{8, "PRINT \"WHAT LIMIT DO YOU WANT\";\n"},
{9, "INPUT L\n"},
{10, "PRINT\n"},
{11, "L1=INT(LOG(L)/LOG(2))+1\n"},
{12, "PRINT \"I'M THINKING OF A NUMBER BETWEEN 1 AND \";L\n"},
{13, "G=1\n"},
{14, "PRINT \"NOW YOU TRY TO GUESS WHAT IT IS.\"\n"},
{15, "M=INT(L*RND(1)+1)\n"},
{20, "INPUT N\n"},
{21, "IF N>0 THEN 25\n"},
{22, "GOSUB 70\n"},
{23, "GOTO 1\n"},
{25, "IF N=M THEN 50\n"},
{30, "G=G+1\n"},
{31, "IF N>M THEN 40\n"},
{32, "PRINT \"TOO LOW. TRY A BIGGER ANSWER.\"\n"},
{33, "GOTO 20\n"},
{40, "PRINT \"TOO HIGH. TRY A SMALLER ANSWER.\"\n"},
{42, "GOTO 20\n"},
{50, "PRINT \"THAT'S IT! YOU GOT IT IN \";G;\" TRIES.\"\n"},
{52, "IF G<L1 THEN 58\n"},
{54, "IF G=L1 THEN 60\n"},
{56, "PRINT \"YOU SHOULD HAVE BEEN ABLE TO GET IT IN ONLY \";L1\n"},
{57, "GOTO 65\n"},
{58, "PRINT \"VERY \";\n"},
{60, "PRINT \"GOOD.\"\n"},
{65, "GOSUB 70\n"},
{66, "GOTO 12\n"},
{70, "FOR H=1 TO 5\n"},
{71, "PRINT\n"},
{72, "NEXT H\n"},
{73, "RETURN\n"},
{99, "END\n"},
{},
};
